# Generated by Django 3.1.5 on 2021-01-15 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210115_2017'),
        ('main_app', '0002_auto_20210115_2019'),
    ]

    operations = [
    ]
