# Generated by Django 3.1.5 on 2021-01-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.CharField(default='replace', max_length=1000),
            preserve_default=False,
        ),
    ]
