# Generated by Django 3.1.5 on 2021-01-20 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_city_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
    ]
