# Generated by Django 3.1.5 on 2021-01-20 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210120_2204'),
        ('main_app', '0007_auto_20210120_2208'),
    ]

    operations = [
    ]
