# Generated by Django 3.1.5 on 2021-01-21 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210120_2307'),
        ('main_app', '0008_auto_20210120_2310'),
    ]

    operations = [
    ]
